wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.001
dropout:
  desc: null
  value: 0.6547588663627012
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692090906.57294
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.17
      5: 0.15.8
      8:
      - 3
      - 5
